spring:
  profiles:
    active: dev
    
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在路径
  type-aliases-package: com.lmx.springcloud.entities  #所有entity别名类所在包
  mapper-locations:
    classpath:mybatis/mapper/**/*.xml  #mapper迎神文件

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                  #数据库连接池的最小维持连接数
      initial-size: 5              #初始化连接数
      max-total: 5                 #最大连接数
      max-wait-millis: 200         #等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://localhost:7001/eureka 单机版
  instance:
    instance-id: dept-8001.com #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip地址

info:
  app.name: lmx-microservicecloud-springcloudconfig01
  company.name: www.baidu.com
  build.artifactId: ${project.artifactId}
  #build.version: $project.version$
  build.version: ${project.version}


