spring:
  profiles:
    active: dev
    
---
server:
  port: 7001 #注册中心占用7001端口，冒号后面必须要有空格

spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client
  

eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名   单机的时候用localhost，集群的时候用域名
  client:
    register-with-eureka: false #false代表不向注册中心注册自己  自己就是注册中心
    fetch-registry: false #false标识自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # 单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务的地址
  #server:
    #enable-self-preservation: false  #禁用eureka的自我保护机制  默认是开启的
    
---

server:
  port: 7001 #注册中心占用7001端口，冒号后面必须要有空格

spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client
  

eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名   单机的时候用localhost，集群的时候用域名
  client:
    register-with-eureka: false #false代表不向注册中心注册自己  自己就是注册中心
    fetch-registry: false #false标识自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # 单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka
      #设置与Eureka Server交互的地址查询服务和注册服务的地址
  #server:
    #enable-self-preservation: false  #禁用eureka的自我保护机制  默认是开启的